services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "2000:2000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb
